In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import cv2
import numpy as np
import warnings 
warnings.simplefilter('ignore')

# load and read image

In [3]:
# load on the image using 'imread' specifying the path to image

img= cv2.imread(r"C:\Users\shaba\OneDrive\deep_learning\cv\image_examples\sir apj abdul kalam.jpg",1)

##  lets take a closer look at how images are stored

In [4]:
print(img)

[[[159 157 156]
  [159 157 156]
  [159 157 156]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[159 157 156]
  [159 157 156]
  [160 158 157]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[160 158 157]
  [160 158 157]
  [160 158 157]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[ 59  41  42]
  [ 60  42  43]
  [ 61  43  44]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[ 59  41  42]
  [ 60  42  43]
  [ 61  43  44]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[ 59  41  42]
  [ 60  42  43]
  [ 61  43  44]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


# shape give the dimension of the image array

In [5]:
img.shape

# the 3d dimensions are 1358 pixel in height * 1500 pixel wide
# 3 means that there are 3 RGB that makeup this image

(828, 564, 3)

# display the image

In [6]:
# to display our image variable , we use imshow

cv2.imshow('sir APJ Abdul Kalam', img)


# waitKey allow us to input information when a image window is open
cv2.waitKey()

# cv2.waitKey(2000) (time in milisecond)

# this close all open window
# failure to place this will cause your program to hang
cv2.destroyAllWindows()

In [7]:
img= cv2.imread(r"C:\Users\shaba\OneDrive\deep_learning\cv\image_examples\sir apj abdul kalam.jpg")
cv2.imshow('pm', img)
cv2.waitKey()
cv2.destroyAllWindows()

# save the image

In [8]:
# 
cv2.imwrite('sir_apj_abdul_kalam.jpg', img)

True

# resize the image

In [9]:
img= cv2.imread(r"C:\Users\shaba\OneDrive\deep_learning\cv\image_examples\sir apj abdul kalam.jpg")

resize = cv2.resize(img,(500,500))

grey = cv2.cvtColor(resize, cv2.COLOR_BGR2GRAY)

cv2.imshow('sir_apj_abdul_kalam', grey)

cv2.waitKey()

cv2.destroyAllWindows()

In [10]:
img.shape[0]*0.5

414.0

In [11]:
img.shape[1]*0.5

282.0

# face Detection Using HAAR Cascade Classifiers

In [12]:
 # we point Open cv cascade classifier function to where our classifier 
face_classifier = cv2.CascadeClassifier(r"C:\Users\shaba\OneDrive\deep_learning\cv\Haarcascades\haarcascade_frontalface_default.xml")

# load our image and convert it to grayscale

img= cv2.imread(r"C:\Users\shaba\OneDrive\deep_learning\cv\image_examples\sir apj abdul kalam.jpg")
img = cv2.resize(img,(500,500))
grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# turning cascade classifier - detectMultiScale ( input image , scaler factor , min neighbors)
faces = face_classifier.detectMultiScale(grey, 1.05,5)

In [13]:
print(faces)

[[202  86 273 273]]


In [14]:
cv2.destroyAllWindows()


In [15]:
face_classifier = cv2.CascadeClassifier(r"C:\Users\shaba\OneDrive\deep_learning\cv\Haarcascades\haarcascade_frontalface_default.xml")

# load our image and convert it to grayscale

img= cv2.imread(r"C:\Users\shaba\OneDrive\deep_learning\cv\image_examples\sir apj abdul kalam.jpg")
img = cv2.resize(img,(500,500))
grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# turning cascade classifier - detectMultiScale ( input image , scaler factor , min neighbors)
faces = face_classifier.detectMultiScale(grey, 1.05,5)

# when no faces detected , face classifier returns and empty tuple 

if faces is ():
    print('no face found')
# we iterate through our faces array and draw rectangle
# over each face in faces

for (x,y,w,h) in faces:
    cv2.rectangle(img, (x,y), (x+w,y+h), (0,255,100),1)
    
cv2.imshow('face detection', img)
cv2.waitKey()
cv2.destroyAllWindows()
    

# face & eye detection 

In [16]:
face_classifier = cv2.CascadeClassifier(r"C:\Users\shaba\OneDrive\deep_learning\cv\Haarcascades\haarcascade_frontalface_default.xml")
eye_classifier = cv2.CascadeClassifier(r"C:\Users\shaba\OneDrive\deep_learning\cv\Haarcascades\haarcascade_eye.xml")


img= cv2.imread(r"C:\Users\shaba\OneDrive\deep_learning\cv\image_examples\sir apj abdul kalam.jpg")
img = cv2.resize(img,(500,500))
grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
faces = face_classifier.detectMultiScale(grey, 1.01,5)

# when no faces detected , face classifier returns and empty tuple 

if faces is ():
    print('no face found')

for (x,y,w,h) in faces:
    cv2.rectangle(img, (x,y), (x+w,y+h), (255,0,0),2)
    roi_grey = grey[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]
    eyes = eye_classifier.detectMultiScale(roi_grey)
    
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color, (ex,ey), (ex+ew,ey+eh),(0,255,0),2)

    
cv2.imshow('face ', img)
cv2.waitKey(0)
cv2.destroyAllWindows()


 # Capture a vedio

In [17]:
# doing some face recognigation with the webcam

import cv2
video =  cv2.VideoCapture(0) # 0--webcam

while True:
    check,frame = video.read()
    gray = cv2.cvtColor(frame , cv2.COLOR_BGR2GRAY)
    cv2.imshow('video', frame)
    if cv2.waitKey(1)==ord('q'):
        break
        
        
video.release()
cv2.destroyAllWindows()

# face & eye detection cascade classifiers

In [18]:

import cv2
face_cascade = cv2.CascadeClassifier(r"C:\Users\shaba\OneDrive\deep_learning\cv\Haarcascades\haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier(r"C:\Users\shaba\OneDrive\deep_learning\cv\Haarcascades\haarcascade_eye.xml")

def detect( grey, frame):
    faces = face_cascade.detectMultiScale(gray,1.3,5)
    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y),(x+w,y+h), (255,0,0),2)
        roi_grey = grey[y:y+h, x:x+w]
        roi_color = frame[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_grey, 1.1,3)
        
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color, (ex,ey), (ex+ew,ey+eh),(0,255,0),2)
    return frame

# doing some face recognition with the webcam

video = cv2.VideoCapture(0)

while True:
    check,frame = video.read()
    grey = cv2.cvtColor(frame , cv2.COLOR_BGR2GRAY)
    cv2.imshow('video', grey)
    canvas = detect(grey,frame)
    
    cv2.imshow('video', canvas)
    if cv2.waitKey(1)==ord('q'):
        break
        
        
video.release()
cv2.destroyAllWindows()        

 # pedistrian detection

In [19]:
import cv2
# create our body classifier
body_classifier = cv2.CascadeClassifier(r"C:\Users\shaba\OneDrive\deep_learning\cv\Haarcascades\haarcascade_fullbody.xml")

# initiate video capture for video file

cap = cv2.VideoCapture(r"C:\Users\shaba\OneDrive\deep_learning\cv\image_examples\walking.avi")

# loop once video is successfully loaded

while cap.isOpened():
    
    # read first frame
    check,frame = cap.read()
    grey = cv2.cvtColor(frame , cv2.COLOR_BGR2GRAY) 
    # pass frame to our body classifier
    
    bodies = body_classifier.detectMultiScale(grey,1.2,3)
    
    # extract bounding boxes for any bodies
    
    for (x,y,w,h) in bodies:
        cv2.rectangle(frame, (x,y),(x+w,y+h), (255,0,0),2)
        cv2.imshow('pedestrian', frame)
    
    
    if cv2.waitKey(1)==ord('q'):
        break
        
        
cap.release()
cv2.destroyAllWindows() 
    

error: OpenCV(4.11.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:199: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [12]:
import time

# Car Detection

In [15]:
car_classifier = cv2.CascadeClassifier(r"C:\Users\shaba\OneDrive\deep_learning\cv\Haarcascades\haarcascade_car.xml")
cap=cv2.VideoCapture(r"C:\Users\shaba\OneDrive\deep_learning\cv\image_examples\cars2.mp4")
while cap.isOpened():
    time.sleep(0.05)
    
    #Read the capture
    check,frame = cap.read()
    grey = cv2.cvtColor(frame , cv2.COLOR_BGR2GRAY)
    
    #pass the frame to our car classifier
    cars = car_classifier.detectMultiScale(grey,1.4,2)
     # extract bounding boxes for any bodies
    for (x,y,w,h) in cars:
        cv2.rectangle(frame, (x,y),(x+w,y+h), (0,255,255),2)
        cv2.imshow('cars', frame)
        
    if cv2.waitKey(1)==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()